services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager_data
      - ./alertmanager/discord_webhook.txt:/etc/alertmanager/discord_webhook.txt
    ports:
      - "9093:9093"
    restart: unless-stopped

volumes:
  prometheus_data: {}
  grafana_data: {}
  alertmanager_data: {}
